name: Build & release app

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install Dependencies
        run: yarn install --network-timeout 300000 --frozen-lockfile

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: yarn run build:linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: yarn run build:mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: yarn run build:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
